module-one:
  - readme.dm
  - settings:
      - __init__.py
      - dev.py
      - prod.py
  - mainapp:
      - __init__.py
      - models.py
      - views.py
      - templates:
          - mainapp:
              - aversion:
                  - a.html
                  - b.html
                  - c.html
                  - both:
                      - 1.html
              - base.html
              - index.html
  - authapp:
      - __init__.py
      - models.py
      - views.py
      - templates:
          - authapp:
              - base.html
              - index.html

module-two:
  - settings:
      - __init__.py
      - dev.py
      - prod.py
  - mainapp:
      - __init__.py
      - models.py
      - views.py
      - templates:
          - mainapp:
              - base.html
              - index.html
  - authapp:
      - __init__.py
      - models.py
      - views.py
      - templates:
          - authapp:
              - base.html
              - index.html

module-three:
  - settings:
      - __init__.py
      - dev.py
      - prod.py
  - mainapp:
      - __init__.py
      - models.py
      - views.py
      - templates:
          - mainapp:
              - base.html
              - index.html
  - authapp:
      - __init__.py
      - models.py
      - views.py
      - templates:
          - authapp:
              - base.html
              - index.html

module-four:
  - settings:
      - __init__.py
      - dev.py
      - prod.py
  - mainapp:
      - __init__.py
      - models.py
      - views.py
      - templates:
          - mainapp:
              - base.html
              - index.html
      - assets:
          - css:
              - style.css
          - js:
              - libs:
                  - 1.js
                  - 2.js
              - main.js
  - authapp:
      - __init__.py
      - models.py
      - views.py
      - templates:
          - authapp:
              - base.html
              - index.html